# Build Speed Optimizations
org.gradle.jvmargs=-Xmx4096m -XX:+UseG1GC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
kotlin.incremental=true

# Android Defaults
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
